### ISSUE TITLE
Make conditional injection inject translated phrases

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#1047]
Right now the conditional injector is set to inject English sentences into the built docs pages. This is fine for the English version of the wikis which are definitely the most read, but it leads to an issue in that English will be injected into the Russian and Chinese versions of the wiki as well.

Ideally we could have a solution that works with our integration with Crowdin but if that's not possible we can perhaps connect to a translation API and inject the translated sentences instead.

related to #1010

**Comment by Swader** [comment]
> Right now the conditional injector is set to inject English sentences into the built docs pages

Not really though. If you have the English MarkDown as such:

> Some sentence. {{ kusama: This is Kusama specific. :kusama }} {{ polkadot: This is Polkadot specific. :polkadot }}. Some other sentence.

Then the injector will, during Kusama operation, create:

> Some sentence. This is Kusama specific. Some other sentence.

But since the sentences are in MD, then translators can just translate them as-is. Example content in Croatian:

> Neka rečenica. {{ kusama: Ovo je specifično za Kusamu. :kusama }} {{ polkadot: Ovo je specifično za Polkadot. :polkadot }} Neka druga rečenica.

Which after conditional rendering in Kusama mode will be:

> Neka rečenica. Ovo je specifično za Kusamu. Neka druga rečenica.

So there's no concern if the translators translate the conditional sentences in MarkDown, which should be the default.

**Comment by lsaether** [comment]
@ansonla3 Can you confirm that this works?

**Comment by ansonla3** [comment]
@lsaether yep. it works

**Comment by lsaether** [comment]
Cool thanks!
