### ISSUE TITLE
Update anonymous proxy

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#1458]
https://wiki.polkadot.network/docs/en/learn-proxies#anonymous-proxies

https://github.com/paritytech/substrate/issues/7735#issuecomment-745443476

And maybe add alternative name "keyless proxy"?

**Comment by joepetrowski** [comment]
Please do no update in this way, for a few reasons.

One, we don't have a new name, or even know that there will be a new name. Changing the name in code means breaking the transaction version, so Ledger and other wallets need to release major versions to stay compatible. It could happen, but it's not a trivial change.

Two, we need to be careful about explaining what things are vs. "what you can do" with things. Examples should strictly contribute to fundamental understanding of a concept/tool and not prescribe use. Abstractions like anon proxies allow for creativity and new account architectures, let's not get it into readers' heads that they are "for" something in particular.

Three, almost everything in the referenced comment is incorrect. (cc @NukeManDan )

![image](https://user-images.githubusercontent.com/25483142/103073871-ae997380-45c8-11eb-8ca0-4c4a3c789e97.png)

No, because that graphic would be incorrect.

> A "keyless account" is akin to a "shell company" that looks and acts like an individual / person on chain (keyed accounts), but in reality is controlled by a dynamic set of "real" keyed accounts.

Also incorrect. What is a "real" account?

> MS do have a single master key (that you technically could find and use to make a MS -> single key control) this "user primary account" does not have a key.

No they do not.

**Comment by nuke-web3** [comment]
@joepetrowski For clarification and for my reference, could you help set these straight?
- A "real" account == is capable of signing, thus able to submit extrinsics (that almost all require in so capacity). Anon Proxies cannot sign, correct?
  - Are there ant other accounts and proxies in substrate or other blockchain project that do not have signing ability of any kind? 
- Multisigs construct a signature that, in theory, can be generated from a single key if you were able to find it. Is this a correct statement? If not, why exactly?

**Comment by joepetrowski** [comment]
- Accounts have nothing to do with signing. They are anything that meets Substrate's trait bound of `AccountId` and have some means of authentication. Maybe you should read this [blog post](https://www.parity.io/building-a-hot-wallet-with-substrate-primitives/).
- Not at all. Look at the multisig code in Substrate.
