### ISSUE TITLE
Para-object: Path to Polkadot

### ISSUE THREAD

**Issue by jplatts12** [w3f/polkadot-wiki#157]
We need a list of possible migration paths and some examples from the real world of how this is being done.

Some teams we are speaking have a liquid ERC-20 token, which is listed and available for trading on exchanges. They want to migrate to be a Parachain with their own on-chain currency. They were concerned about the specifics of transitioning from one to the other with minimal community and liquidity costs.

One of the best things we can do is a lock/burn contract on Ethereum, which can then be used to bootstrap claims on the Parachain
- One implementation detail, do they plan to support multiple imports of the contract? Or is it like "you either move your tokens by this date or else you don't get them"?
- Binance did their migration using a deadline.
- The lock/burn approach is being used by some of these teams because it is the common trend when migrating tokens between chains. This how we are doing it for Polkadot too. The DOT token has a placeholder as an ERC20 on Ethereum and it will be migrated to Polkadot on launch.

Having an example side chain of this would also be cool to link from the Wiki. Shawn from Parity might be able to ideate on this more or even code something up if Tech Ed can coordinate with them that would begreat.

**Comment by Swader** [comment]
IMO it's a bit of a hard sell parachains as the go-to strategy aren't all that viable for a large number of projects (and we want as many as possible to move!). In reality few even well established ERC20-powered projects in Eth (regardless of the volumes of liquidity they have) will be able or willing to afford a slot. IMO we should be demoing migration paths that focus more on parathreads or better yet migration to a de-facto tokenchain that we spin up in one of the reserved slots, rather than try and sell the dedicated chain story to each and every project which, ultimately, has the exact same thing under the hood (a simple ERC20 token). My 2 mDOT.

**Comment by DannyS03** [comment]
https://wiki.polkadot.network/docs/build-pdk

**Comment by salmad3** [comment]
We have content that briefly points to some of the items mentioned in the original issue, although the comments Bruno left seems like the most viable approach.

This is similar to the conflict I felt with: https://github.com/w3f/polkadot-wiki/issues/286

We can focus on the smart contract platforms that have secured a slot on Kusama.
- [x] Moonriver
- [ ] Shiden

> Others examples in the ecosystem:
> - Edgeware
> - Acala’s upcoming DeFi Smart Contract Platform

Then, **bridge parachains** and **parathreads**
