### ISSUE TITLE
Add more info for non-relay chain consensus options

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#164]
emily
"can you conduct state transitions without the relay chain or is it required for every state transition?"
question of the day
peter
you can, then you have 2 choices: either you have your own temporary consensus or you wait for inclusion in the relay chain for consensus
we should have something longer on the wiki for it

**Comment by Swader** [comment]
Does this basically refer to parathreads and/or non-polkadot-connected substrate chains?

**Comment by lsaether** [comment]
It applies to both parathreads or parachains. The two options are produce blocks one-to-one with the relay chain and therefore have high security on every block; or produce blocks more quickly and only have relay chain security at every included block.

**Comment by joepetrowski** [comment]
There are no non-relay chain consensus options. Polkadot guarantees valid **state transitions** not valid **states.** If you execute a block outside the context of the relay chain then you've violated all trust guarantees that Polkadot provides.

**Comment by krichard410** [comment]
If this is a common question, we could include this as a question in the Parachain [FAQ section](https://wiki.polkadot.network/docs/en/learn-parachains#faq)?

**Comment by Swader** [comment]
We should, but we're not at 100% on the answer here. The way it goes right now is:

- a parachain's collators submit a block candidate to the RC, the RC finalizes, and the collators can build the next block only on this finalized block. They don't HAVE to submit in the next RC slot (i.e. all went offline), but once they do, it has to be built on the last finalized one provided by the RC.
- a parathread's collators submit a block candidate by bidding on the thread slot. The RC finalizes if the collator won the bid, and the collators can build the next block only on this finalized block. **The parathread cannot continue building itself and submit only occassional blocks to the RC** - it MUST build on the last finalized block. So for a parathread which only submits a block once per _period_ (like a music copyright parathread), the collators would have to make sure they monitor how many pending transactions there are, whether or not they fit into a block candidate, and submit it to RC before that limit is reached. If they wait past the block limit, then some transactions will wait for another _period_. The good thing is that parathreads and parachains can define their own block size so they can have them as big as they need them.

Another thing to note in the Parathread case: since the blocks are not actually being built, only TXs are being compiled for eventual inclusion into a block candidate, the state of the parathread is always outdated to connecting clients and outside observers, unless they decide to read the TX pool and apply what's in there to the current state to form a quasi-state before finalization by the RC.

Is this accurate @joepetrowski?

**Comment by joepetrowski** [comment]
It's mostly accurate according to what we know now.

> the collators can build the next block only on this finalized block

This would be really slow, since there can be a long unfinalized head. So the parachain has to reference a parent RC block, but it doesn't need to be finalized. But if there are competing unfinalized chains on the RC, the parachain has to say which one it's working within.

> parathreads and parachains can define their own block size so they can have them as big as they need them.

I'm sure there will be some weight limit because we have to keep execution time within 2 seconds. This is still an open question AFAIK.

> the state of the parathread is always outdated to connecting clients and outside observers, unless they decide to read the TX pool and apply what's in there to the current state to form a quasi-state before finalization by the RC.

Right, but I think "outdated" probably isn't the best word. It is up-to-date in the sense that it's the last finalized state. But if someone wants to make a transaction that depends on another transaction that has not been finalized, then that dependency needs to be written in some way (e.g. using a nonce to indicate order of execution from an account).
