### ISSUE TITLE
Conversion of Derivation Paths

### ISSUE THREAD

**Issue by defyreofficial** [w3f/polkadot-wiki#1742]
Derivation paths typically follow this type of format: https://learnmeabitcoin.com/technical/derivation-paths, e.g. m/44/0/0... etc.

How can one convert this type of path to Polkadot's derivation paths?

More specifically, SafePal for example uses m/44h/354h/0h as the derivation path but there is no mention in the Wiki's or other documents on how to convert this standard derivation path into Polkadot's version of it.

**Comment by netsuke1** [comment]
Each coin has its own derivation path(s) by definition.
BIP 44 cannot be converted. It only says where e.g. in a seed recovery the wallet should search for the BTC coins, because there are many, many possibilities. If BIP 44 is supported, the wallet should search in derivation path m/44'/0'/0'. There the HD-Wallet would find BTC coins with a 1's address. The question is rather if Safe Pal supports the derivation path m/44'/354'/0'/0' (i.e. Polkadot)?

**Comment by netsuke1** [comment]
Hardware Wallet SafePal S1 version 1.0.28: 
The wallet supports BTC derivation path recovery according to 
BIP 44: m/44'/0'/0' (for 1addresses).
As it seems 
BIP 49: m/49'/0'/0' (for 3addresses) and 
BIP 84: m/84'/0'/0' (for bc1addresses) are not supported. 
Does anyone have other experiences?

**Comment by Swader** [comment]
Please ask in https://github.com/paritytech/subport
