### ISSUE TITLE
Add diff between Polkadot and Westend for devs

### ISSUE THREAD

**Issue by jakehemmerle** [w3f/polkadot-wiki#1802]
Known notable differences are:
- Existential deposit: 1 DOT vs 0.01 WND
- multisig deposit: ~20 DOT vs 1 WND

0.01 would make it seem like Westend did not go through the 100x upgrade, but that doesn't explain why multisig deposit isn't off by the same factor.

As @laboon suggested, we can do a diff on the runtimes:

DOT:
https://github.com/paritytech/polkadot/tree/master/runtime
and here in Polkadot : https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L231

Westend: https://github.com/paritytech/polkadot/blob/58ff7f59e9a9e43f5b1e30a126ee023a41af9d39/runtime/westend/src/lib.rs#L207

**Comment by Swader** [comment]
This is going to change on both chains, and there's plenty more testnets. What is the long term benefit of diffing them for users vs. just listing the links on which they can find this out?

If we can automate this with a github action + script so the diff page is kept up to date, I'm for it, but otherwise I think it's a bit of a waste of time.

**Comment by jakehemmerle** [comment]
If mainnet and westend are constantly changing and the differences are going to be just in the runtime, links to the runtimes sounds sufficient. I wasn't sure where to find the differences for the two.

I'll figure out a place to add "check the runtimes for differences" with links or something similar.
