### ISSUE TITLE
References to Kusama w/o Polkadot mentioned

### ISSUE THREAD

**Issue by nuke-web3** [w3f/polkadot-wiki#1842]
I can enumerate if needed, here is one example:https://wiki.polkadot.network/docs/en/maintain-sync

Throughout the _Polkadot_ wiki, Kusama is referenced where Polkadot should be (I think)

**Comment by salmad3** [comment]
Hi @NukeManDan,

Do you mind pointing to the docs in the wiki you feel Polkadot should be referenced (instead of Kusama). It doesn't have to be an exhaustive list. From my understanding, there are guides that still reference Kusama as they did in pre-Polkadot days, but I wasn't sure if some sections should be referencing Polkadot repos or if the tutorials do intend to use Kusama still.
