### ISSUE TITLE
Review staking - ensure all points are updated and fix outdated information

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#202]
Add clarifications:

- explain about controller and stash accounts, explain about reward distribution choice (compound, controller, stash)
- explain the unbonding period and how to find out how long it is.

Somewhat related, is there an on chain const of slots per era? Couldn't find it.

**Comment by joepetrowski** [comment]
> Somewhat related, is there an on chain const of slots per era? Couldn't find it.

Technically no, because era is a GRANDPA concept and slots are a BABE concept. There is a const number of slots per _epoch,_ and an epoch == a session. Normally six sessions comprise an era, but an era can be forced based on the Council or slashable offenses.

**Comment by joepetrowski** [comment]
Add:
- Fix mentions of validator commission being a fixed value (it is a percent). E.g. https://wiki.polkadot.network/docs/en/learn-staking#4-rewards-mechanism

> The second point to note is that each validator candidate is free to name their desired commission fee (as a fixed amount of DOTs) to cover operational costs.

**Comment by Swader** [comment]
@ansonla3 are you on this?

**Comment by krichard410** [comment]
Is this still an issue? And should this information go on the staking page?

**Comment by lsaether** [comment]
Yes it is still an issue. I think what needs to be done is review of the staking page with special attention of the 3 points mentioned in this thread:

- Reward distribution is properly explained. E.g. Why would someone send to their controller instead of the stash? When should they automatically bond rewards? 
- The page demonstrates how to check the unbonding period and the remaining unbonding time for a staker.
- Mentions of validator commission should talk about percentage amounts not fixed rates.
