### ISSUE TITLE
Update for Secure Validator page

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#214]
From Mo -

Miny minor comment on this
An example of highly available, secure setup would be a layer of sentry nodes in front of multiple validators connected to a single signing machine. This machine could implement signing logic to avoid equivocation, even if an attacker gained access to a validator node

https://wiki.polkadot.network/docs/en/maintain-guides-secure-validator

HA setup would require multiple key servers too, with a load balancer in front

**Comment by ansonla3** [comment]
afaik proper HA setup is not ready now if manage those signing keys without a software like Cosmos [KMS](https://github.com/tendermint/kms) would be very dangerous. since you know validator's equivocation would slash more than just offlin.

**Comment by ansonla3** [comment]
@fgimenez any thoughts?  correct me if I am wrong

**Comment by fgimenez** [comment]
AIUI until delegated signatures are in place a setup like that could be hard to implement. 

There's a team that proposed a very similar solution to grants (they have it working on other networks), but AFAIK they haven't started working on it yet. There are other teams working on other HA approaches maybe people from grants can give more info.

**Comment by lsaether** [comment]
We shouldn't explicitly recommend HA set-ups since it's too easy to shoot yourself in the foot by using one unless you _really_ know what you're doing. Closing this issue for now until 1) delegated signatures are in substrate that enables HA set-ups 2) someone creates a good KMS that prevents double signing and has tested it extensively that we can tell people to use or 3) a robust, well architectured recipe and guide is available similar to @fgimenez secure validator repo.
