### ISSUE TITLE
Explain fishermen better

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#221]
We should go more into depth on what fishermen do and how they do it.

What do fisherman report other than equivocation?

They might not even be able to report equivocations. We might restrict that to validators.
The main thing we need fishermen for is to rise incorrect attestations of the validity of parachain blocks.
Because with parachains only a few validators are watching.

**Comment by joepetrowski** [comment]
Fishermen don't report equivocations at all AFAIK. Votes are gossiped amongst validators and equivocation is easy to detect and doesn't require voting - if you have two votes from the same validator, the signatures are cryptographic proof of equivocation.

The main thing fishermen do is increase the validity threshold of validators necessary to finalize a block. So normally you might need half of a parachain's validators to attest to its validity just to enter the tx queue. Then you need 13 more validators to reconstruct the PoV from the erasure coding and attest to its validity. If a fisherman flags a candidate as invalid, then the threshold goes from 13 to >1/3 of the entire validator set.

If more than 1/3 of the validator set say "actually this is valid" then the fisherman is slashed. If more than 1/3 of the validator set agree that it is invalid, then those who marked it as valid are slashed.

The case of more than 1/3 of the validator set reporting it valid and more than 1/3 reporting it invalid is not considered since it breaks the assumption that less than 1/3 of the set is faulty.

**Comment by Swader** [comment]
Is this final or in flux? Is it documented somewhere in code too from where we could maybe grab this in greater detail and do a writeup?

**Comment by joepetrowski** [comment]
> Is this final or in flux? Is it documented somewhere in code too from where we could maybe grab this in greater detail and do a writeup?

https://github.com/w3f/research/blob/master/docs/papers/AnV/AnV-2-protocols.tex#L158

See also Section IV of this: https://medium.com/polkadot-network/the-path-of-a-parachain-block-47d05765d7a
