### ISSUE TITLE
Unable to access wiki docs in other languages

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2333]
When we select other languages from dropdown menu on top right side of the website, it simply redirects to docs in English

**Comment by nam-hle** [comment]
Hi @DrW3RK, I want to continue to fix the issue. But it is relate to configure the Github **secret** environment variables. So please contact my Discord nam-hle#6450.

**Comment by nam-hle** [comment]
I'm willing to continue to fix that issue. It's from my Docusarus migration work. Will have a PR soon 😍

**Comment by DrW3RK** [comment]
@nam-hle Can you confirm if the wiki is being rendered in different languages now? I just tried, but I do not see any change

**Comment by nam-hle** [comment]
The deploy actions are failed due to Crowdin issue. I tested locally and there is no error. Can you please do the following steps for me to double-check:
- Create a .env file at the root directory with the following variables (from current project setting on Github), then run `polkadot2:build`
![ảnh](https://user-images.githubusercontent.com/28835226/125773935-7b33917b-1bb9-4864-91b1-d12371bbcfa2.png)
- If it does not work, help me edit the Crowdin config file by wrap env variable with quotes as the instructions https://support.crowdin.com/configuration-file/#api-credentials-from-environment-variables
- Otherwise, I will reopen the created issue in Crowdin CLI repo

Sorry for inconvenient
