### ISSUE TITLE
Polkadot brand updates to the Wiki

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#2881]
Update the Wiki with the latest brand guidelines wherever required - https://polkadot.network/brand-assets/

**Comment by DrW3RK** [comment]
Preliminary updates to the Wiki Navbar, Footer and favicon are performed through this PR https://github.com/w3f/polkadot-wiki/pull/2884

A broader review of Wiki content needs to be done before closing this issue.

**Comment by salmad3** [comment]
Only thing I came across was an image or two in the "Interact with Polkadot" section on the Getting Started page that could be updated, and the videos that are embedded which have the old Polkadot logo, which is on the video end. 

I will close this issue as of now since we are using "Polkadot" as the logo for the Wiki, and not updating to "Polkadot Wiki".
