### ISSUE TITLE
Mythbusting Page

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#298]

**Comment by Swader** [comment]
Should this go under FAQ or be a separate thing?

**Comment by lsaether** [comment]
Can go into a FAQ. Will need to dig up the myths and post them here....

**Comment by Swader** [comment]
- polkadot wishes eth dead
- on-chain governance cannot work
- polkadot is plutocratic (see above)
- eth is better because it supports 200k+ validators vs polkadot's "maybe 1000" - hardest one to beat because there's no formal explanation from our side why we're not doing BLS aggregation and using the same scaling gains
- no one will build parachains if they can lose them due to auctions, and if apps built on parachains can be hurt by this, there's no way to ensure that parachain owner will keep their lease, so apps become ephemeral by default
