### ISSUE TITLE
Add a header for "Contribution Welcome"

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#318]

**Comment by Swader** [comment]
What's this?

**Comment by lsaether** [comment]
I think it's not clear that the wiki wants outside contributors.

My thought here is that we can have a banner that shows above the header that says "contributions are welcome! click here to learn how to get started" that links to the contributing page.

**Comment by Swader** [comment]
A corner flag like one of those "fork this project" might be handy here - instead of fork this project, it could say "Improve this wiki" or something like that, and lead to the contributing page. That way it's not a new header that's in everyone's face, but it's also always present slightly out of the way.

See #330 for example implementation.
