### ISSUE TITLE
Add more bidding examples for Parachain slot auctions

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3225]
https://wiki.polkadot.network/docs/learn-auction#examples

From Bill

> I would put in a few more examples - what happens if Emily and Dave win (they split the parachain slot for the two different lease ranges), and what happens if Frank (or some other "F" name) bids 1000 DOT and wins, but only for range 1 -2, and nobody bids for any LPs 3 - 8. Or if Frank bids 1000 DOT for range 1 - 2, and someone else bids 50 DOT for range 1 - 8, and those are the only bids.

Add more examples like above, probably by citing a real auction bid scenario 

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/86818441/163333708-5e6196b3-0c8c-4d3a-98d8-e07c4ad93b0c.png">

**Comment by paolo-penna** [comment]
I might be missing something important (apologize). Below a few thoughts/examples (also inspired by the comments above).


I start with the same example from [https://wiki.polkadot.network/docs/learn-auction#examples](https://wiki.polkadot.network/docs/learn-auction#examples):

**Example 1** (C = Charlie wins all 8 slots): 
[auction.pdf](https://github.com/w3f/polkadot-wiki/files/8769973/auction.pdf)

**Example 2** (a new bidder F = Frank joins and beats C, but only wants the last 4 slots): 
[auction2.pdf](https://github.com/w3f/polkadot-wiki/files/8770065/auction2.pdf)
Now the first 4 slots are ``free'' (Charlie does not win anymore) and they can be assigned to D = Dave:
[auction2.1.pdf](https://github.com/w3f/polkadot-wiki/files/8770078/auction2.1.pdf)


**Example 3** (both Dave and Emily have rather high valuations for their respective intervals, so that they jointly beat Charlie):
[auction3.pdf](https://github.com/w3f/polkadot-wiki/files/8770125/auction3.pdf)
It may be possible that (with these valuations) Dave may get better (lower) price by bidding less, still enough to win jointly with Emily (their sum exceed 600 = Charlie's bid):
[auction3.1.pdf](https://github.com/w3f/polkadot-wiki/files/8770173/auction3.1.pdf)
During the auction, Dave may face the following dilemma:  bid less than the true valuation (100 x 4 = 400) hoping that someone will join the auction for some of the last 4 slots, in order to ``kick out'' Charlie
[auction4.pdf](https://github.com/w3f/polkadot-wiki/files/8770220/auction4.pdf)

The tendency/temptation to underbid (report less than the true valuations) during the auction is counterbalanced by the ``candle mechanism'', that is, not knowing when exactly the auction will end, it exposes Dave to the risk of loosing the slots (I think).
