### ISSUE TITLE
Improve learn-comparison page

### ISSUE THREAD

**Issue by emresurmeli** [w3f/polkadot-wiki#3301]
- [ ] Avalanche, 
- [ ] Cosmos
- [ ] Ethereum 2.0
- [ ] Polygon
- [ ] Near

**Comment by DannyS03** [comment]
should be careful here when drawing comparison - Avalanche and Near are good ones. There are already dedicated comparison pages for Cosmos and Ethereum 2.0 that can be updated. I'd also add Polygon, now that Polygon has something similar to the parachain model with Polygon Supernets.

Because of the existing efforts for comparisons, another initiative the Wiki can take on is comparing tech stacks and specific solutions. For instance: XCM vs. IBC, Substrate vs Cosmos SDK, etc.

Something to consider in the future is comparisons that distinguish **architectures of interoperability** (which can include XCM & IBC). There is a new wave of solutions for multi-chain, cross-chain interoperability offered by networks like Axelar, Layer Zero, Synapse, Connext, Nomad, Multichain, etc.

**Comment by muddlebee** [comment]
Here's a nice one on comparison of Heterogeneous Blockchain Networks. Avax, Cosmos and Polkadot
https://medium.com/@arikan/a-comparison-of-heterogeneous-blockchain-networks-4bf7ff2fe27

It got a nice infographic as well 
![image](https://user-images.githubusercontent.com/8139783/168488859-dff63942-4a2a-4802-a846-99b581a7e60a.png)

**Comment by filippoweb3** [comment]
This issue can be resolved with the [Wiki reorg](https://github.com/w3f/polkadot-wiki/issues/4376)

**Comment by filippoweb3** [comment]
@CrackTheCode016 @DrW3RK I think we can close this PR. There are no changes and I feel this is not a priority. Let me know what you think!
