### ISSUE TITLE
Add warning for Identity usage

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#3516]
re onchain identity: since set identity calls go on chain, there has been reports of people immediately receiving emails from registrars to lure them towards a particular provider, and these could easily turn into phishing attacks.. and we received reports about [homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack) on polkadot.js when showing url associated to an account.. other wallets could be vulnerable too.. i wonder if it makes sense to add some sort of warning on the wiki so people understand this is a decentralized system and identities can't be trusted in any meaningful sense.. 

https://wiki.polkadot.network/docs/learn-identity#format-caveat looks like a step towards a warning in my view

**Comment by DrW3RK** [comment]
I'm trying to draft a caution for this. Let me know if my chain of thought is factually correct -

- The set identiy calls go on-chain. Hence, the contact information is available publicly for legitimate service providers like registrars and scammers who might impersonate them
- The strings in the identity fields are good candidates for homograph attacks, as someone can list web3.f0undation as their website instead of web3.foundation and also can get verified by the registrar (if the checks are automated)!
- In a decentralized network, one should be cautious making transactions with accounts solely based on their identity. If an account on-chain claims to be of Web3 Foundation, it is wise to verify its authenticity by checking directly with Web3 Foundation or examining the established history of that account on-chain.

**Comment by DrW3RK** [comment]
@michalisFr may be relevant for Identity support articles as well https://github.com/w3f/polkadot-wiki/issues/3346

**Comment by keeganquigley** [comment]
@DrW3RK Added this [here](https://support.polkadot.network/a/solutions/articles/65000181981).

**Comment by lamafab** [comment]
FYI: https://github.com/paritytech/substrate/issues/11820

**Comment by DrW3RK** [comment]
Closing the issue. The cautionary note is available in the support doc https://support.polkadot.network/support/solutions/articles/65000181981 which is referenced in the Wiki doc on identity.

The caution is added to the Wiki doc as well https://github.com/w3f/polkadot-wiki/pull/3581/commits/ced129d23cd0651a6ac57235b6aecd7b6fd1cee9
