### ISSUE TITLE
Ambiguity with Decimals

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3539]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/86818441/179400237-f88bf2cc-a733-4470-bf50-6cb18f520162.png">

In some parts of the world, the numbers in the article above are read as a hundred thousand and five hundred thousand, which can be misleading. https://www.quora.com/Why-do-some-people-use-the-comma-instead-of-the-dot-for-larger-numbers

We need to refine the `human readable token`code to incorporate this https://github.com/w3f/polkadot-wiki/blob/master/scripts/fetch.mjs

**Comment by alfarok** [comment]
@DrW3RK just to clarify the goal of this task is to abide by the scientific notation standard shown in the link in the description?

`1 000.000 instead of 1000.000` (formatter doesn't currently apply commas)

This doesn't resolve the issue shown in the description though.

`100.000 would still be 100.000`

We could drop trailing zeros but you could still encounter the issue.

`100.125 is still 100.125`

Maybe I am missing something here?  I would think this must happen a lot in crypto.

**Comment by DrW3RK** [comment]
I would say, displaying in decimals should only be triggered if the value indeed has decimals. Most of Polkadot's values are in multiples of DOTs. 

Take the example of existential deposit. It is 1 DOT. If we use this 'humanReadableToken`tag, it shows up as 1.000 DOT, which is interpreted as a thousand DOT by someone in Germany and France https://www.grammar-monster.com/lessons/commas_with_numbers.htm

**Comment by DrW3RK** [comment]
When I skimmed through the Wiki, sometimes we use , separator and sometimes we use . separator. As we are moving away from hardcoding values, it makes sense to standardize this and avoid ambiguity wherever possible.

**Comment by DrW3RK** [comment]
Most of the Kusama values are fractional. So, a humanReadableToken for Kusama displays 6 decimal points, which is okay. I somehow find the DOT values confusing on the Wiki

**Comment by alfarok** [comment]
Sounds good, we can definitely do a couple small things to improve this.  Like you said, just dropping the extra 0's would help.  Since most the values in the repo are not fraction it should fix at least of handful of occurrences.

[Here](https://github.com/w3f/polkadot-wiki/blob/a3d146e5269adadeb2fa457276fe0138366135ec/components/RPC-Connection.jsx#L140) is where the new human readable filter code lives in the new React component.
