### ISSUE TITLE
Update Regex for Status Badge Update

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3674]
https://github.com/w3f/polkadot-wiki/pull/3673 Right now, there are two badges displayed

https://github.com/w3f/status-badges/blob/b19b918177fd1fad95e297b848953e38ec25eac4/modules/mod.js#L72 This is the relevant function

"what I would try first is modify this part of the regex (?<emoji>\:\w+\:)? to capture utf8 emojis as well" - Lucas

**Comment by alfarok** [comment]
This possibly stems from [this change](https://github.com/w3f/polkadot-wiki/pull/3660/files#diff-252591e5b4735a8e3fce5505dd9c340bc4a7763e7a39c3b7ffa969d22dbd6492L21-R23):
```
From:
active-emoji: ':green_heart:'
stale-emoji: ':yellow_heart:'
inactive-emoji: ':broken_heart:'

To:
active-emoji: '🟢'
stale-emoji: '🟡'
inactive-emoji: '🔴'
```

If we use,
```
:green_circle:
:yellow_circle:
:red_circle: 
````
it may resolve the issue.  I have noticed in the past that not all emojis decode the same in the GitHub and Docusaurus markdown rendered views.  They probably use slightly different parsing logic.

As a first debugging step I am going to make the change outlined above and try to manually trigger the action.  If this doesn't resolve it I will dig into the regex code.

**Comment by alfarok** [comment]
Manually invoking the action with the change from above produces this:

![image](https://user-images.githubusercontent.com/13341935/185964425-23646161-9ea4-4d7f-92e0-604fb1ed7b6c.png)

which made me realize I also need to manually swap the existing emojis in [docs/build/build-open-source.md](https://github.com/w3f/polkadot-wiki/blob/d84e6118b165876e810b764786e681f31b575a03/docs/build/build-open-source.md) with their equivalents in order to properly swap.

I will make another PR and run another test in an hour or so, as to not exhaust the GitHub API rate-limiter.

**Comment by alfarok** [comment]
Looking into the regex logic now

**Comment by alfarok** [comment]
Addressed by Lucas
