### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module 

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#3686]
```
Error:  Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/polkadot-wiki/polkadot-wiki/node_modules/unist-util-visit/index.js from /home/runner/work/polkadot-wiki/polkadot-wiki/scripts/injectPlugin.js not supported.

Instead change the require of index.js in /home/runner/work/polkadot-wiki/polkadot-wiki/scripts/injectPlugin.js to a dynamic import() which is available in all CommonJS modules.

```
Error surfaced when trying to merge this dependabot PR https://github.com/w3f/polkadot-wiki/pull/3679
https://github.com/w3f/polkadot-wiki/runs/7968499614?check_suite_focus=true

**Comment by alfarok** [comment]
@DrW3RK 
I am not 100% sure but after some research I think fixing this issue is blocked by:
https://github.com/facebook/docusaurus/issues/6520

The error occurs because the latest version of `unist-util-visit` that is installed now only supports ES modules and no longer supports `require(...)`?  Adding `"type":"module"` to the package.json file, along with converting several import statements gets you past the initial error but eventually leads to the Docusaurus issue above.  It doesn't seem like Docusaurus supports ES Modules yet.  As of July 4th, their fix is on-hold because of another legacy yarn dependency used by the package.

**Comment by DrW3RK** [comment]
Alright. We can wait for this to be fixed. Till then, we can stop merging dependabot PRs related to this

**Comment by alfarok** [comment]
I am going to close this since there is no open dependabot PR and we need to wait on updates from Docusaurus to adequately address this conflict in the future.  We can revisit the next time `unist-util-visit` updates hoping a bump in the Docusaurus version will address the issue with no effort on our part.
