### ISSUE TITLE
prod deploy stopped working

### ISSUE THREAD

**Issue by DrW3RK** [w3f/polkadot-wiki#4349]
After #4333 there was no successful deployment to the github pages

Temporarily fixed it by enabling manual workflow dispatch on prod branch https://github.com/w3f/polkadot-wiki/pull/4348

**Comment by alfarok** [comment]
I checked yesterday and the `prod` branch was up-to-date with master.  It looks like the CI successfully ran 14 hours ago -> https://github.com/w3f/polkadot-wiki/actions/runs/3991680757/jobs/6846732621.  I think the new job that rebases `prod` is working but the existing jobs that build and deploy to GH Pages for Polkadot and Kusama are not detecting the pushes that happen in the rebasing job.  This is weird to me because the initial job clearly invokes the line `git push` as the final step.  I will have to spend some time testing to see exactly what is happening.

**Comment by DrW3RK** [comment]
https://github.com/w3f/polkadot-wiki/pull/4357
