### ISSUE TITLE
Issues with "Polkadot Validator Setup" page of the Validator Guide

### ISSUE THREAD

**Issue by IkerAlus** [w3f/polkadot-wiki#4488]
The ["Polkadot Validator Setup" page](https://wiki.polkadot.network/docs/maintain-guides-how-to-use-polkadot-validator-setup) of the Validator Guide is referencing its content to a archived and unmaintained [GitHub repository](https://github.com/w3f/polkadot-validator-setup). Also, it has been discussed that the _nginx_ proxy should not be used in front of the P2P port  and the linked repo does. 

It would be nice to update the wiki page and/or link a maintained repo to avoid future issues.

**Comment by muddlebee** [comment]
@IkerAlus 
> nginx proxy should not be used in front of the P2P port and the linked repo does.

what is the alternative way for this?

also if you or anyone would like to maintain the archived repo you can apply for the grants here https://github.com/w3f/Grants-Program or applying through the treasury https://wiki.polkadot.network/docs/learn-treasury

I was thinking of maintaining this, but due to time bandwidth I didn't pick this up. let me know if you need help around this :)

**Comment by DrW3RK** [comment]
Thank for bringing this to our notice @IkerAlus We are removing the outdated docs and will re-create them when we have an updated repo
