### ISSUE TITLE
Set up a Full Node: Fast install instructions for Linux don't work

### ISSUE THREAD

**Issue by davidkhl** [w3f/polkadot-wiki#541]
https://wiki.polkadot.network/docs/ru/maintain-sync
OS: Ubuntu 18 and 20 LTS,
No message after sudo chmod +x polkadot
Fast install instructions for Linux don't work. I have an error: 
bash: ./polkadot: cannot execute binary file: Exec format error

**Comment by lsaether** [comment]
It's strange that it works on neither Ubuntu 18 or 20 since it was probably built on one or the other of these. However, binary compatible can't really be guaranteed for every architecture so the best we can do in these instructions to add a note saying what you can do if it doesn't work. Namely, you will need to build it from source or use docker.
