### ISSUE TITLE
Update ICMP

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki#55]
There's new information on ICMP that needs to be integrated into the ICMP page on the wiki:

[Gav's write-up](https://github.com/paritytech/polkadot/wiki/ICMP)
[Research write-up](https://research.web3.foundation/en/latest/polkadot/networking/4-icmp/)

**Comment by Swader** [comment]
I know you've got this in progress but just dropping this here as a few reminders that we talked about should be clarified:

- why do validators not always pass messages?
- how is state bloat addressed in terms of message hash storage on chain? You could purge all older than current finalized block, but this does not work for threads (see below). There's also no way to actually purge the stuff - if it's in a block it's in a block. If we have pruning we can just remove blockchain data, sure, since we have finalization, but anyone re-syncing from scratch gets all that bloat until their sync process is ready to prune.
- what about island chains that have no common collator with other chain collators?
- when chains ICMP, then it's okay to keep the message for a single block really because a block produced while there are still pending messages (who scans for this btw? What if there are more messages than fit in a block?) won't be valid, so the queue must be empty during block production. However, in threads this doesn't work - a thread may not produce a block for a long time, so how long does one keep a pending message?

Possible solution:

- since threads are in the same environment, direct communication could be possible with only proof of executed communication sent to the relay chain. Threads need different collators anyway, so maybe this is a local customization that'll be needed for those. In other words, make messages in a thread slot non-essential for relay chain block production.

**Comment by Swader** [comment]
ICMP needs to be updated to XCMP (crosschain?) across the board due to https://en.wikipedia.org/wiki/Internet_Control_Message_Protocol

**Comment by Swader** [comment]
Closing this for now, the page is reasonably up to date, to whatever info we have. When Gav fleshes out the XCMP predecessor he announced recently, we can open a new issue.
