### ISSUE TITLE
Linking TechEd videos to Wiki

### ISSUE THREAD

**Issue by krichard410** [w3f/polkadot-wiki#570]
It might be helpful for new users (or visual learners) to watch a TechEd video after reading a page on the wiki.

**Comment by Swader** [comment]
Out of curiosity, did you mean link in text, or embed them? 

The problem with too many video embeds is they make the page heavier and slower to load, and we'd need several per page in some cases where a page covers a big part of the functionality. 

I'd personally prefer just plain links, because that also might play well with #63, better than videos. Maybe a custom styling for video links - that could make them stand out but not be invasive.

**Comment by krichard410** [comment]
@Swader Great question! I was thinking of linking the video through some text/links, I like your suggestion though with the custom styling to make them stand out. Perhaps something like _italicized_?

**Comment by laboon** [comment]
Yes, definitely links, not embedded.  The wiki should be pretty lightweight and videos should be linked.  Italicized or something would be fine but not necessary, just stating that they are videos should be enough.

Call me old-fashioned, but I _hate_ embedded videos (and auto-playing videos are, I am convinced, the plot of some diabolical fiend from the netherworld).  If I want to watch a video, I will go to a page with a video playing; if I want to read, I should be able to read.

`</rant>`

**Comment by Swader** [comment]
Agreed.

I think a nice stand-out that's non-invasive would be better, but that's just me liking to have separation of visual context. For example, observe the colored side-quotes here: https://hackmd.io/Bf57SOYmRPytsNooSZzVVw
