### ISSUE TITLE
Validate Dune Data

### ISSUE THREAD

**Issue by filippoweb3** [w3f/polkadot-wiki#6061]
There is a discrepancy in the number of extrinsics shown on the Wiki and the one shown on Dot Lake: https://dashboards.data.paritytech.io/parachains.html

I believe in the wiki unsigned txs are included.

Also, it would be great to include a detailed description of the variable that is shown on the charts, as shown in Dot Lake

![Screenshot 2024-07-05 at 16 27 11](https://github.com/w3f/polkadot-wiki/assets/110459737/45462a1e-07f5-44f7-bb18-d8231851de71)

@mkchungs can you have a look?

**Comment by mkchungs** [comment]
Thanks for bring it to our attention. our team will look into it

**Comment by CrackTheCode016** [comment]
It appears this page has the option to run queries but are not populated: https://wiki.polkadot.network/docs/general/dune-analytics/polkadot-dashboards/polkadot-dot-ordinals

**Comment by filippoweb3** [comment]
@mkchungs lmk what is the progress on this issue, thanks :)

**Comment by mkchungs** [comment]
Hey @filippoweb3, Thanks for checking in again. @deadline314 has already updated the [query logic](https://dune.com/queries/3924669) to only consider signed extrinsics.

We have also added [relevant descriptions for the ecosystem metrics charts](https://dune.com/queries/3547412/6413909). Since Dune doesn't support description hovering/hiding, we have decided to keep the descriptions succinct to avoid being overly descriptive on methodology.

![Screenshot 2024-07-24 at 8 06 36 AM](https://github.com/user-attachments/assets/b1144d99-c7bb-452f-a615-bcc02369d92d)

**Comment by filippoweb3** [comment]
@mkchungs great! I close this issue :) thank you for addressing all the points, including the one pointed out by @CrackTheCode016
