### ISSUE TITLE
Wiki cleanup: General section

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-wiki#768]
The wiki has grown too cluttered. There is content duplication (index page of the Learn section vs Getting started, for example) and there's human written content that's severely outdated (roadmap). Here are my suggestions on what to do:

- [x] Remove learn-roadmap
- [x] Remove learn-relevant-links or merge with another document. It does get *some* traffic, but is largely orphaned. We should consider moving the links like the 4 papers from the getting started page into this page, and then linking to it from the getting started page, i.e. "Polkadot has published four different papers, each for a specific audience. They're listed and described in the *Polkadot Papers* section of our Relevant Links page."
- [x] The intro prose from learn-introduction can be an intro for getting-started, and the links from that page can go into relevant links, each in their own section. Basically, keeping links in a single page where we can actually keep track of them would make keeping the list up to date easier. The content of the learn-introduction prose intro + getting started should then replace the current learn-introduction page's content.
- [ ] Community can be merged with relevant links too imo
- [x] Getting started should be near the top of the General section, above or below the wiki index
- [x] The wiki index should be updated. Ideally, we should have a starting point for each type of user.

This will clean up the General section a bit. We can look at the others after that.

Thoughts @lsaether @krichard410?

**Comment by krichard410** [comment]
Going to loop in @joepetrowski for more feedback too :) 

@Swader this is a great idea! Just so I understand though, the new General section will look like:
Wiki Index
Getting Started
Claims
Contributing
FAQ
Glossary 
Community
Grants
Redenomination of DOT
Research Pages

Could we reorder the links a bit? Something like this, ordered with level of importance:
Wiki Index
Getting Started
Claims
Redenomination of DOT
Grants
Research Pages
Community
Contributing
Glossary 
FAQ

Are we getting rid of community page altogether? I think we should keep it, as it directs users to our socials. We could merge this in with getting started, but it might make the page too long. 

For your fourth point there, could we instead link each link to their appropriate wiki page instead of merging it with community? (example: the Governance Demo link could be placed on the governance page, etc.). I think deleting a learn-relevant-links page and just linking the links in their desired location makes more sense than having a separate page to have to look for. 

Another thing I'm wondering if we should have Substrate links throughout the learn-relevant-links page, I don't know if it's necessary for the polkadot wiki to hold information about Substrate. 

I was also thinking that it might make more sense to merge the wiki index within the getting started page. Both are similar in the sense that they are welcoming a new user to the wiki, so it seems redundant IMO to have both pages. From my own experience, I use the getting started page more than the wiki page as it contains a clear guidance on where to begin on the network. The getting started page is intuitive for people without a technical background and the link is located in the main navigation. 

Ah - this comment has become a lot longer than I anticipated, if anything doesn't make sense, let me know. What are your thoughts on this? =)

**Comment by lsaether** [comment]
> Remove learn-roadmap

I'll submit a PR because we should do this ASAP. I think this might be why we still get questions like "When does Polkadot launch?" 

However, at one point we had a "builder's roadmap" that more or less pointed people to the relevant GitHub task boards to track progress. I think this is something to bring back since we're doing less of telling people calendar dates and more of listing goals that need to be reached to progress to the next milestone.

> relevant-links

Agreed with @krichard410 that we don't need to keep a list of Substrate resources, we can delegate Substrate content to the Susbtrate developer docs instead. As for the rest of the links on that page I think we can disperse them to the wiki page that relates best to them and remove this page.

> community page

I vote to keep it, especially since we can augment it with the script that scrapes Polkaproject to add community projects there.

> wiki-index

The wiki index is redundant imo, since it's acting as a psuedo front page. If there's anything we would miss when removing it we should augment the front page of the wiki with those links.

**Comment by krichard410** [comment]
@Swader were you working on this task or can anyone take it? =)

**Comment by Swader** [comment]
Anyone can take any part, just tag this issue in the PR you submit so I know which checkbox to tick when it's done and so someone else doesn't grab something already grabbed.

**Comment by krichard410** [comment]
@Swader  for your third point there:

> The intro prose from learn-introduction can be an intro for getting-started, and the links from that page can go into relevant links, each in their own section. Basically, keeping links in a single page where we can actually keep track of them would make keeping the list up to date easier. The content of the learn-introduction prose intro + getting started should then replace the current learn-introduction page's content.

If we merge the learn-introduction and the getting started together into one page, would we need to get rid of the "Getting Started" button in the navigation? Because the "Getting started" and the "Learn" button at that point would lead to the same place. What do you think?

**Comment by Swader** [comment]
Anything that reduces the number of pages while not making content overwhelming is a-ok in my book :)

**Comment by krichard410** [comment]
@Swader Could I close this issue? =) 
The community page seemed to be voted that it should stay as it is

**Comment by Swader** [comment]
Yep go for it!
