### ISSUE TITLE
Encourage Parity Signer and provide more documentation

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-wiki#884]
We should try to encourage use of Parity Signer

Perhaps have a "migrate to Parity Signer" page based on this - https://github.com/paritytech/parity-signer/blob/master/docs/tutorials/Recover-Account-Polkadotjs.md

**Comment by laboon** [comment]
Hey @lsaether , I'm going to take this if you don't mind.  I just went through it and so have all the docs and pics ready.

**Comment by salmad3** [comment]
It would seem that this is covered in: https://wiki.polkadot.network/docs/learn-account-generation#parity-signer & https://wiki.polkadot.network/docs/learn-account-restore#parity-signer. Aside from adding some additional statements that encourage the use parity signer, the pages account for the process in: https://github.com/paritytech/parity-signer/blob/master/docs/tutorials/Recover-Account-Polkadotjs.md

I believe this can be closed, and if we wanted to create a page that shows a complete end-to-end guide on setting up and migrating to parity signer, we can discuss that (e.g. steps to factory reset device and stay offline - getting parity signer on the device - etc...). 

Please reopen if otherwise.
